In [116]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [117]:
dataset = pd.read_csv('data-penumpang-bus-sekolah-bulan-januari.csv')
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, -2].values

In [118]:
print(x)

[[1.250e+02 5.203e+03]
 [      nan       nan]
 [3.000e+01 6.920e+02]
 [7.000e+01 1.232e+03]
 [2.400e+01 2.330e+02]
 [9.500e+01 4.887e+03]
 [      nan       nan]
 [      nan       nan]
 [      nan       nan]
 [      nan       nan]
 [      nan       nan]
 [1.200e+01 1.040e+02]
 [2.100e+01 2.780e+02]
 [      nan       nan]
 [1.800e+01 1.910e+02]
 [      nan       nan]
 [3.100e+01 1.593e+03]
 [3.100e+01 1.272e+03]
 [5.800e+01 3.162e+03]
 [5.800e+01 1.757e+03]
 [      nan       nan]
 [2.700e+01 6.940e+02]
 [2.000e+01 2.880e+02]
 [2.900e+01 2.500e+02]
 [3.100e+01 4.250e+02]
 [1.030e+02 3.912e+03]
 [      nan       nan]
 [      nan       nan]
 [      nan       nan]
 [1.000e+02 2.192e+03]
 [3.100e+01 1.419e+03]
 [3.100e+01 1.870e+03]
 [      nan       nan]
 [1.200e+01 1.170e+02]
 [      nan       nan]
 [      nan       nan]
 [6.200e+01 9.010e+02]
 [      nan       nan]
 [      nan       nan]
 [2.300e+01 2.340e+02]
 [6.200e+01 5.388e+03]
 [9.200e+01 3.617e+03]
 [6.200e+01 3.627e+03]
 [7.400e+01

In [119]:
print(y)

[125.  nan  30.  70.  24.  95.  nan  nan  nan  nan  nan  12.  21.  nan
  18.  nan  31.  31.  58.  58.  nan  27.  20.  29.  31. 103.  nan  nan
  nan 100.  31.  31.  nan  12.  nan  nan  62.  nan  nan  23.  62.  92.
  62.  74.  92.  24.  nan  26.  nan  47.  68.  nan  nan  nan  nan  nan
  nan  nan  nan  20.  39.  20.  nan  49.  28.  nan  20.  91.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1. 

In [120]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [121]:
print(x)

[[1.25000000e+02 5.20300000e+03]
 [           nan 1.69337379e+02]
 [3.00000000e+01 6.92000000e+02]
 [7.00000000e+01 1.23200000e+03]
 [2.40000000e+01 2.33000000e+02]
 [9.50000000e+01 4.88700000e+03]
 [           nan 1.69337379e+02]
 [           nan 1.69337379e+02]
 [           nan 1.69337379e+02]
 [           nan 1.69337379e+02]
 [           nan 1.69337379e+02]
 [1.20000000e+01 1.04000000e+02]
 [2.10000000e+01 2.78000000e+02]
 [           nan 1.69337379e+02]
 [1.80000000e+01 1.91000000e+02]
 [           nan 1.69337379e+02]
 [3.10000000e+01 1.59300000e+03]
 [3.10000000e+01 1.27200000e+03]
 [5.80000000e+01 3.16200000e+03]
 [5.80000000e+01 1.75700000e+03]
 [           nan 1.69337379e+02]
 [2.70000000e+01 6.94000000e+02]
 [2.00000000e+01 2.88000000e+02]
 [2.90000000e+01 2.50000000e+02]
 [3.10000000e+01 4.25000000e+02]
 [1.03000000e+02 3.91200000e+03]
 [           nan 1.69337379e+02]
 [           nan 1.69337379e+02]
 [           nan 1.69337379e+02]
 [1.00000000e+02 2.19200000e+03]
 [3.100000

In [122]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [123]:
print(x_train)

[[           nan 1.69337379e+02]
 [1.00000000e+00 1.90000000e+01]
 [1.00000000e+00 8.00000000e+00]
 [1.80000000e+01 1.91000000e+02]
 [1.00000000e+00 2.50000000e+01]
 [1.00000000e+00 7.00000000e+00]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 2.40000000e+01]
 [1.00000000e+00 9.00000000e+00]
 [1.00000000e+00 1.80000000e+01]
 [2.80000000e+01 5.26000000e+02]
 [           nan 1.69337379e+02]
 [1.00000000e+00 7.00000000e+00]
 [1.00000000e+00 6.00000000e+00]
 [1.00000000e+00 1.20000000e+01]
 [1.00000000e+00 9.00000000e+00]
 [1.00000000e+00 5.00000000e+00]
 [1.00000000e+00 1.00000000e+01]
 [1.00000000e+00 1.70000000e+01]
 [1.00000000e+00 1.80000000e+01]
 [1.00000000e+00 7.00000000e+00]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 2.80000000e+01]
 [1.00000000e+00 1.00000000e+01]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 7.00000000e+00]
 [1.00000000e+00 7.00000000e+00]
 [1.00000000e+00 1.20000000e+01]
 [1.00000000e+00 8.00000000e+00]
 [4.90000000e+01 1.56200000e+03]
 [1.000000

In [124]:
print(x_test)

[[1.00000000e+00 3.20000000e+01]
 [1.00000000e+00 9.00000000e+00]
 [1.00000000e+00 2.10000000e+01]
 [1.00000000e+00 1.40000000e+01]
 [1.00000000e+00 1.00000000e+01]
 [1.00000000e+00 6.00000000e+00]
 [2.10000000e+01 2.78000000e+02]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 7.00000000e+00]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 1.10000000e+01]
 [1.00000000e+00 5.00000000e+00]
 [1.00000000e+00 7.00000000e+00]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 1.00000000e+01]
 [2.70000000e+01 6.94000000e+02]
 [1.00000000e+00 9.00000000e+00]
 [           nan 1.69337379e+02]
 [           nan 1.69337379e+02]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 1.10000000e+01]
 [           nan 1.69337379e+02]
 [1.00000000e+00 8.00000000e+00]
 [1.00000000e+00 1.70000000e+01]
 [1.00000000e+00 1.10000000e+01]
 [1.00000000e+00 1.20000000e+01]
 [1.00000000e+00 9.00000000e+00]
 [1.00000000e+00 6.00000000e+00]
 [1.00000000e+00 1.30000000e+01]
 [1.00000000e+00 1.90000000e+01]
 [1.000000

In [125]:
print(y_train)

[ nan   1.   1.  18.   1.   1.   1.   1.   1.   1.  28.  nan   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.  49.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  58.   1.
   1.   1.   1.   1.   1.  20.   1.   1.   1.   1.   1.   1.   1.  31.
   1.   1.   1.  31.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  12.   1.
   1.  nan  92.   1.   1.  20.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.  nan   1.   1.   1.   1.   1.   1.   1.   1. 100.   1.   1.
   1.  nan   1.   1.   1.   1.  nan  30.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.  nan   1.   1.   1.   1.
   1.   1.  91.  31.   1.   1.   1.   1.   1.   1.   1.  62.   1.   1.
   1.   1.  nan   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  31.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  58.   1.   1.   1.
  70.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1. 

In [126]:
print(y_test)

[ 1.  1.  1.  1.  1.  1. 21.  1.  1.  1.  1.  1.  1.  1.  1. 27.  1. nan
 nan  1.  1. nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. nan  1.  1.  1. nan  1.  1.
  1. nan  1. 39.  1.  1. nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 20.
  1.  1.  1. nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 47. nan  1.
 nan 24.  1.  1. 24.  1.  1.  1.  1. nan  1. 95.  1.  1.  1. nan  1.  1.
 20.  1.  1.]


In [127]:
from sklearn.preprocessing import  StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [128]:
print(x_train)

[[            nan -2.89757431e-02]
 [-2.74246447e-01 -2.28261129e-01]
 [-2.74246447e-01 -2.42842594e-01]
 [ 6.92794868e-01 -2.60037883e-04]
 [-2.74246447e-01 -2.20307602e-01]
 [-2.74246447e-01 -2.44168181e-01]
 [-2.74246447e-01 -2.42842594e-01]
 [-2.74246447e-01 -2.21633190e-01]
 [-2.74246447e-01 -2.41517006e-01]
 [-2.74246447e-01 -2.29586716e-01]
 [ 1.26164270e+00  4.43811854e-01]
 [            nan -2.89757431e-02]
 [-2.74246447e-01 -2.44168181e-01]
 [-2.74246447e-01 -2.45493769e-01]
 [-2.74246447e-01 -2.37540243e-01]
 [-2.74246447e-01 -2.41517006e-01]
 [-2.74246447e-01 -2.46819357e-01]
 [-2.74246447e-01 -2.40191418e-01]
 [-2.74246447e-01 -2.30912304e-01]
 [-2.74246447e-01 -2.29586716e-01]
 [-2.74246447e-01 -2.44168181e-01]
 [-2.74246447e-01 -2.42842594e-01]
 [-2.74246447e-01 -2.16330839e-01]
 [-2.74246447e-01 -2.40191418e-01]
 [-2.74246447e-01 -2.42842594e-01]
 [-2.74246447e-01 -2.44168181e-01]
 [-2.74246447e-01 -2.44168181e-01]
 [-2.74246447e-01 -2.37540243e-01]
 [-2.74246447e-01 -2

In [129]:
print(x_test)

[[-0.25891643 -0.15251706]
 [-0.25891643 -0.2010009 ]
 [-0.25891643 -0.17570498]
 [-0.25891643 -0.19046094]
 [-0.25891643 -0.19889291]
 [-0.25891643 -0.20732488]
 [ 1.40554632  0.36604921]
 [-0.25891643 -0.20310889]
 [-0.25891643 -0.20521689]
 [-0.25891643 -0.20310889]
 [-0.25891643 -0.19678491]
 [-0.25891643 -0.20943287]
 [-0.25891643 -0.20521689]
 [-0.25891643 -0.20310889]
 [-0.25891643 -0.19889291]
 [ 1.90488515  1.24297429]
 [-0.25891643 -0.2010009 ]
 [        nan  0.13698917]
 [        nan  0.13698917]
 [-0.25891643 -0.20310889]
 [-0.25891643 -0.19678491]
 [        nan  0.13698917]
 [-0.25891643 -0.20310889]
 [-0.25891643 -0.18413696]
 [-0.25891643 -0.19678491]
 [-0.25891643 -0.19467692]
 [-0.25891643 -0.2010009 ]
 [-0.25891643 -0.20732488]
 [-0.25891643 -0.19256893]
 [-0.25891643 -0.17992097]
 [-0.25891643 -0.17570498]
 [-0.25891643 -0.20521689]
 [-0.25891643 -0.19256893]
 [-0.25891643 -0.19256893]
 [-0.25891643 -0.2010009 ]
 [-0.25891643 -0.20310889]
 [-0.25891643 -0.20521689]
 

In [130]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train,y_train)

ValueError: ignored

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min()-1, stop = x_set[:,0].max()+1, step=0.01),
                     np.arange(start = x_set[:, 1].min()-1, stop = x_set[:,1].max()+1, step=0.01))
plt.contourf(x1,x2, classifier.predict(np.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),
              alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(x1.min(), x1.max())
plt.ylim(x2.min(), x2.max())
for i, j in enumerate (np.unique(y_set)):
    plt.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Training Set)')
plt.xlabel('Model')
plt.ylabel('MPG')
plt.legend()
plt.show()